the-capital-hub/safety-online

store/cartStore.js
- avoid TypeError when cart API returns items without `product`
- centralize cart product mapping with `transformCartProducts`
=> fix cart product mapping when product is null

components/BuyerPanel/home/FeaturedSection.jsx, components/BuyerPanel/home/Home.jsx
- Conditionally render the home page's `FeaturedSection` only when top selling, best selling, or featured products are available.
- Inside `FeaturedSection`, hide individual subsections when their data arrays are empty to prevent blank UI or errors.
=> Hide empty sections on home page

app/(buyers)/checkout/page.jsx, app/api/admin/orders/[id]/invoice/route.js, app/api/admin/orders/route.js, components/AdminPanel/Popups/InvoicePopup.jsx, components/AdminPanel/Popups/OrderDetailsPopup.jsx, components/AdminPanel/Popups/UpdateOrderPopup.jsx, components/BuyerPanel/account/tabs/SubComponents/OrderDetailPopup.jsx, lib/generateInvoicePDF.js, lib/invoicePDF.js, lib/orders/createOrder.js, lib/orders/email.js, lib/utils/gst.js, model/Order.js, model/SubOrder.js, store/checkoutStore.js
- add reusable GST helpers and use them to calculate totals during checkout, order creation, and admin flows
- extend order and sub-order persistence to capture GST breakdowns and expose them via the admin APIs
- refresh email and PDF invoice generation to render IGST/CGST/SGST line items instead of a generic tax row
=> Add GST breakdown support across order workflows

components/AdminPanel/Popups/AddProductPopup.jsx, components/AdminPanel/Popups/BulkProductUploadPopup.jsx, components/AdminPanel/Popups/UpdateProductPopup.jsx
- restrict the admin product subcategory field to existing category subcategories during add and edit flows
- reset invalid or stale subcategory selections when the category changes
- extend the admin bulk upload template and parser to include a product subcategory column
=> Implement subcategory selection and import support

app/api/admin/coupons/route.js
- add a helper to normalize boolean payloads coming into the admin coupon API
- ensure POST and PUT handlers use the helper so toggles work with string payloads
=> Fix boolean parsing for admin coupon toggles

app/coming-soon/page.jsx, components/BuyerPanel/NavigationBar.jsx
- replace the buyer navigation bar's dynamic category list with a static menu that routes every entry to a coming soon experience
- add a dedicated coming soon page that shows tailored messaging based on the selected menu item and offers quick navigation back to live areas
=> Update buyer navigation to use coming soon menu

app/coming-soon/page.jsx, components/BuyerPanel/NavigationBar.jsx
- replace the static navigation strip with categories fetched from the admin API and support subcategory dropdowns
- send visitors to the products list when items exist or to the coming-soon view when a category/subcategory is empty
- enhance the coming-soon page copy so dynamic category details render cleanly, including parent context for subcategories
=> feat: dynamic category navigation bar

app/admin/catalog/coupons/page.jsx
- remove the preview action button from the coupons management table in the admin panel
- drop the unused Eye icon import now that the preview action is gone
=> Remove coupon preview action button from admin coupons table

components/AdminPanel/Popups/AddProductPopup.jsx, components/AdminPanel/Popups/UpdateProductPopup.jsx, components/SellerPanel/Products/AddProductPopup.jsx, components/SellerPanel/Products/UpdateProductPopup.jsx
- replace the duplicate key feature fields in admin add/update product popups with a single textarea and normalize submission data
- mirror the streamlined key feature editing experience in the seller add/update product popups so it matches the product detail view
=> Simplify product feature capture in product popups

lib/invoicePDF.js
- read the GST rate directly from order data with a default fallback for invoice generation
- format GST percentage labels consistently so IGST, CGST, and SGST percentages render correctly throughout the PDF
=> Fix IGST rate displayed on invoice PDF

components/AdminPanel/Popups/AddProductPopup.jsx, components/AdminPanel/Popups/UpdateProductPopup.jsx
- enforce automatic discount calculation and price validation in the add and update product popups
- restrict HSN codes to eight digits and annotate measurement labels with their units
- fix the update product popup so price fields are initialized before validation, preventing reference errors
=> Fix update product popup price initialization

app/api/admin/categories/route.js, app/api/categories/route.js, lib/categoryCounts.js
- add a reusable helper that aggregates published product totals for each category and sub-category and optionally persists the counts
- use the shared helper in the admin categories endpoint so the management table shows accurate product totals
- update the public categories endpoint to return the same computed counts for the navigation menu
=> Fix category product counts across admin and navigation

app/api/products/[id]/route.js
- add reusable helpers to normalise category and subcategory names to regex variants when building related product queries
- prioritise matching the active product's subcategory when fetching related products and fall back to category-only matches
- guard the product lookup to return a 404 before computing review aggregates when an invalid id is supplied
=> Improve related product retrieval by subcategory

app/api/products/route.js
- normalize subcategory filters by aggregating all matching id, slug, and name variants before querying products
- reuse cached published categories to resolve category ids/slugs to names and keep category filtering consistent even when subcategory is supplied
=> Improve category and subcategory matching

app/api/products/route.js
- add an inline MongoDB expression helper that slugifies subcategory fields before comparison to avoid runtime errors in the products API
=> Fix missing slug expression helper in products API

app/api/products/route.js
- remove the MongoDB $regexReplace-based slug helper from the products API
- rely on regex-driven conditions when filtering products by subcategory
=> Fix subcategory filtering for MongoDB compatibility

store/authStore.js, store/cartStore.js, store/wishlistStore.js
- add a logout helper to the auth store that clears the client session and redirects to the login screen when invoked
- update cart and wishlist stores to treat 401 responses as expired sessions, reuse the logout helper, and show a clear session-expired toast
- ensure cart promo removal awaits the server response so unauthorized sessions are caught before showing success
=> Handle expired tokens by logging out users

app/seller/orders/page.jsx
- add fallbacks when downloading seller shipment receipts so missing order numbers do not crash the page
- guard seller order table cells against absent order details to avoid runtime errors
=> Handle missing order metadata in seller orders page

app/seller/account-settings/page.jsx, components/SellerPanel/Settings/address.jsx, components/SellerPanel/Settings/form.jsx, store/sellerCompanyStore.js
- add a dedicated seller company Zustand store to centralize fetching, saving, and uploading assets for company data
- update the seller account settings page to enforce authentication, surface loading/error states, and reuse the shared company store
- refactor the company profile and address components to consume the shared store, add validation messaging, and disable actions while mutations run
=> Make seller account settings dynamic with centralized company store

components/AdminPanel/ReturnsPage.jsx
- add inline guidance on the admin returns page that points to the settings toggle for enabling or disabling buyer returns
=> Add settings guidance to admin returns page

app/admin/analytics/page.jsx, app/api/admin/analytics/route.js, components/AdminPanel/AdminSidebar.jsx, components/AdminPanel/Analytics/AdminAnalytics.jsx, store/adminAnalyticsStore.js
- add a comprehensive `/api/admin/analytics` endpoint that authenticates admins, applies rich filters, and returns marketplace, seller, and customer performance data
- introduce an admin analytics store, route, and UI that surface filters, charts, exports, and seller/customer reports in the admin panel
- expose the new analytics experience in the admin sidebar navigation
=> Add admin analytics dashboard with comprehensive reporting

app/admin/catalog/categories/page.jsx, app/api/admin/categories/route.js, app/api/categories/route.js, app/api/products/filters/route.js, app/api/products/route.js, components/AdminPanel/Popups/AddCategoryPopup.jsx, components/AdminPanel/Popups/UpdateCategoryPopup.jsx, model/Categories.js, store/adminCategoryStore.js
- add UI controls to capture and edit category navigation order values within the admin list and popups
- persist the navigation order field through the API, data model, and exports while sorting public category endpoints accordingly
=> Add navigation order management to admin categories

app/admin/catalog/categories/page.jsx
- ensure inline category navigation order commits use the latest drafted value before saving
- update the navigation order input handlers to pass the current field value and keep drafts in sync after a successful save
=> Fix inline category navigation order updates

components/AdminPanel/PaymentsPage.jsx
- update the admin payments page to read Zustand store slices individually
- prevent React's getServerSnapshot infinite loop error on /admin/payments
=> Fix admin payments selectors to stop infinite render loop

app/admin/catalog/products/page.jsx
- add inline quick edit controls for MRP, sale price, and stock on the admin products table
- validate quick edit values before saving and reuse the existing update product workflow with toasts for feedback
- disable conflicting actions while saving quick edits to prevent concurrent edits
=> Add quick edit controls for admin product pricing and stock

app/api/notifications/[id]/route.js, app/api/notifications/route.js
- switch the notifications API routes to use the named dbConnect export
=> Fix notifications API dbConnect import usage

app/api/admin/payments/[id]/approve/route.js, app/api/admin/payments/route.js, app/api/seller/payments/route.js, app/seller/orders/page.jsx, app/seller/payments/page.jsx, components/AdminPanel/PaymentsPage.jsx, lib/payments/releaseEscrowPayment.js, model/Payment.js
- add an admin approval state for escrow payments and expose an approval API that records payout metadata
- update the admin and seller payment views to highlight pending approvals and capture transaction details before release
- extend the payment schema and release helpers to store admin approval history and payout references
=> Add admin approval step for escrow payouts

app/api/admin/payments/[id]/approve/route.js, app/api/admin/payments/route.js, app/api/seller/payments/route.js, app/seller/orders/page.jsx, app/seller/payments/page.jsx, components/AdminPanel/PaymentsPage.jsx, lib/payments/releaseEscrowPayment.js, model/Payment.js
- ensure the Payment model re-registers the schema when the admin approval status is missing
- prevent validation failures when moving payments into the admin approval state
=> Fix admin approval enum on Payment model

app/api/admin/payments/route.js
- avoid filtering admin payment stats by the current status filter
- ensure released payout totals remain visible after an approval
=> Ensure released payout totals ignore status filter

app/api/seller/auth/register/route.js, app/seller/(auth)/register/page.jsx, model/SellerBankDetails.js, store/sellerAuthStore.js, zodSchema/sellerRegistrationSchema.js
- add reusable seller registration zod schemas that cover personal, company, and bank information along with helpers
- create a SellerBankDetails model and update the seller registration API to store validated company and bank data while handling duplicates
- rebuild the seller registration page into a multi-step experience wired to the new schema and update the auth store to report loading state correctly
=> feat: expand seller registration with company and bank details

components/BuyerPanel/products/ProductDetail.jsx
- ensure the pincode serviceability form stacks vertically on small screens
- allow the input to stretch and make the action button full width before the small breakpoint
=> Fix pincode serviceability form layout

lib/reports/shipmentLogger.js
- replace the shipment logging persistence layer with an in-memory store to avoid writing to `logs/shipment-logs.json`
- retain existing filtering utilities while keeping only the most recent entries in memory
=> Stop persisting shipment logs to file

app/api/admin/sellers/route.js
- remove the extra closing brace in the seller creation handler to restore valid syntax
=> Fix seller API handler block closure

app/admin/store/promotion-banners/page.jsx, app/api/admin/brand-promotions/[id]/route.js, app/api/admin/brand-promotions/route.js, app/api/home/route.js, app/api/upload/route.js, model/BrandPromotion.js
- update the upload handler to stream images to Cloudinary via base64, return metadata, and improve error messaging
- persist Cloudinary public IDs for brand promotions across creation, updates, deletes, and surface them through the admin and home APIs
- adjust the admin promotion banner form to manage Cloudinary metadata when uploading, editing, or reusing banner images
=> Fix promotion banner uploads to persist Cloudinary metadata

app/api/upload/route.js
- import the Cloudinary configuration helpers in the upload API route so configuration checks work at runtime
=> Fix Cloudinary config check import

app/api/seller/company/upload-logo/route.js
- reuse the shared Cloudinary configuration helper in the seller company logo upload route
- return a clear error response when required Cloudinary environment variables are missing before attempting an upload
=> Fix Cloudinary configuration handling for seller logo upload

app/(buyers)/checkout/page.jsx, app/api/user/addresses/route.js, components/BuyerPanel/account/tabs/MyProfile.jsx, components/BuyerPanel/account/tabs/SubComponents/AddressFormDialog.jsx, lib/invoicePDF.js, lib/orders/email.js, model/User.js, store/checkoutStore.js, zodSchema/addressSchema.js
- remove the billing address type from address validation, persistence, and API handling so every saved address is treated as a ship-to location
- simplify checkout and profile address management UIs to list and capture only shipping details
- update order communications to reference the delivery address instead of a billing address
=> Remove billing address support

components/BuyerPanel/cart/MiniCart.jsx
- ensure the mini cart sidebar layout supports overflow scrolling by allowing flex children to shrink
- keep the cart items container scrollable for long lists
=> Fix mini cart sidebar scroll behavior
