the-capital-hub/safety-online

components/BuyerPanel/home/ProductCard.jsx, components/BuyerPanel/home/ProductCardVarient.jsx, components/BuyerPanel/products/ProductCard.jsx, components/SellerPanel/HomePage/ProductCard.jsx
- make product card components link to their `/products/[id]` page across buyer and seller views
- attach onClick handlers so whole cards open the product detail screen
=> Ensure product cards navigate to product details

app/(buyers)/products/[id]/page.jsx
- resolve 404s on product detail pages by computing a valid API base URL and falling back to the request host
=> fix: ensure product route uses valid base URL

components/AdminPanel/AdminSidebar.jsx
- open and highlight admin sidebar sections based on current route
=> feat: dynamic admin sidebar active states

app/api/admin/product/bulkUploadProduct/route.js, components/AdminPanel/Popups/BulkProductUploadPopup.jsx
- allow admin bulk upload of products using CSV or JSON in UI
- convert drive image links to googleusercontent and map CSV rows to product schema
- save provided images during bulk upload API
=> feat: support csv bulk product upload

app/api/admin/product/bulkUploadProduct/route.js, app/api/products/bulk-upload/route.js, app/api/seller/product/bulkUploadProduct/route.js
- Automatically create missing categories during admin bulk product uploads and update counts
- Apply the same category validation when sellers bulk upload products
- Handle category creation and count updates in generic bulk upload API
=> Ensure categories exist during bulk product uploads

components/BuyerPanel/home/Home.jsx
- remove TrustedCompanies component so section no longer appears on home page
=> refactor: remove trusted companies section from home

app/admin/catalog/products/page.jsx, components/AdminPanel/Popups/AddProductPopup.jsx, components/AdminPanel/Popups/BulkUpdateProductsPopuup.jsx, components/AdminPanel/Popups/UpdateProductPopup.jsx
- load categories from the database for admin product filters
- fetch category list in admin add/update/bulk update product popups
=> feat: use dynamic categories from category management

app/api/product/[id]/route.js, app/api/products/[id]/route.js, app/api/products/route.js, components/BuyerPanel/products/ProductCard.jsx, components/SellerPanel/LandingPage/ProductCard.jsx
- compute average product ratings in product list and detail APIs
- display per-product star ratings in buyer and seller product cards
- expose rating field from product endpoints
=> feat: show dynamic product ratings

lib/invoicePDF.js
- restyle the generated invoice PDF with a branded layout and accent header
- add client, order snapshot, totals, notes, and signature sections for a polished presentation
- improve helpers for currency/date formatting and balance due calculations
=> feat: refresh invoice pdf design

lib/invoicePDF.js
- restyle the invoice PDF to use the shared branding, typography, and spacing from the reference design
- reorganize header, billing/shipping details, order metadata, and notes to follow the standardized layout
- refresh the product table and totals rendering to keep tax information and balances consistent with the unified template
=> Align invoice PDF layout with platform design

app/(buyers)/order-success/page.jsx, app/api/admin/product/bulkUploadProduct/route.js, app/api/seller/product/bulkUploadProduct/route.js, app/seller/(auth)/register/page.jsx, components/SellerPanel/Products/BulkProductUploadPopup.jsx, lib/invoicePDF.js
Bulk Product Upload Popup for 
1. Admin panel 
2. Seller panel
=> Bulk Product Upload Popup

app/not-found.js
- add a global not-found page for unmatched routes with guidance messaging
- provide a prominent button that brings users back to the homepage
=> Add custom 404 page with home navigation

components/AdminPanel/Popups/AddProductPopup.jsx, components/AdminPanel/Popups/UpdateProductPopup.jsx
- enforce automatic discount calculation and price validation in the add and update product popups
- restrict HSN codes to eight digits and annotate measurement labels with their units
=> Adjust product popup pricing validation and labels

app/api/admin/categories/route.js, components/AdminPanel/Popups/AddCategoryPopup.jsx, model/Categories.js
- add a published flag to subcategory schema and normalize existing category responses
- persist subcategory publication state through admin create and update flows
=> Fix subcategory publication mapping

app/(buyers)/products/page.jsx, app/api/categories/route.js, app/api/products/filters/route.js, components/BuyerPanel/NavigationBar.jsx, lib/slugify.js, store/productStore.js
- expose stable slugs for categories and subcategories from the public APIs
- update the navigation bar and product store to consume slug-aware categories and drive routing
- normalize product listing parameters with shared slug utilities to keep filtering consistent
=> Normalize navigation categories by slug

app/api/products/route.js
- normalizes subcategory filter slugs against stored category data so requests return matching products
- expands the list of acceptable subcategory value variants to handle special characters such as ampersands
=> Fix subcategory filtering in products API

app/api/products/route.js
- enhance subcategory filtering by generating a MongoDB expression that slugifies stored values
- combine regex and slug-expression checks so updated subcategory slugs still return associated products
=> Improve subcategory product filtering

app/api/products/route.js
- simplify subcategory filtering by relying on variant-based regex matching when admin updates rename subcategories
- filter product image data so empty strings do not reach the frontend image component
=> Simplify subcategory query and clean images

app/seller/(auth)/login/page.jsx
- Refresh the seller login layout with a full-screen gradient backdrop and animated feature highlights
- Introduce structured feature cards and an updated hero illustration presentation for large screens
- Restyle the authentication form with glassmorphism accents, improved typography, and vibrant CTA states
=> Redesign seller login page

app/seller/account-settings/page.jsx
- wait for the seller auth store to hydrate before redirecting or fetching company data on the account settings page
- add hydration event listeners and a loading fallback so the page renders reliably once authentication is available
=> Fix hydration flow in seller account settings page

app/api/seller/analytics/route.js, app/seller/analytics-report/page.jsx, store/sellerAnalyticsStore.js
- add a seller analytics API that aggregates revenue, order, customer, and category insights with robust filter support
- create a seller analytics store to manage filters, fetch data, and export reports to CSV for sellers
- rebuild the seller analytics page with marketplace-style filters, charts, distribution insights, and downloadable reports
=> Add seller analytics API and advanced reporting UI

model/Order.js
- replace the random order number default with a deterministic invoice number generator
- add a pre-validate hook that issues numbers in the LSI-SOYY-00001 format for the current year
=> feat: generate yearly invoice numbers

app/(buyers)/checkout/page.jsx
- allow cart checkouts to use the coupon entry and recommended coupon list on the checkout page
- reuse cart store promo APIs so shoppers can apply or remove coupons without leaving checkout
- show the applied cart coupon with consistent messaging alongside recommended offers
=> Enable coupon selection during cart checkout

app/seller/notifications/page.jsx, components/SellerPanel/Layout/NotificationDropdown.jsx
- replace the seller notification dropdown with live data from the shared notification store, including archive and navigation actions
- rebuild the seller notification center to use dynamic notification data, filtering, grouping, and actionable controls backed by the store
=> Revamp seller notification center

components/SellerPanel/Products/AddProductPopup.jsx, components/SellerPanel/Products/UpdateProductPopup.jsx
- rename the seller add and update product popups' regular price label to MRP
- validate that a provided sale price is lower than the MRP before submitting the form
=> Update seller product popups with MRP label and validation

app/api/seller/auth/forgot-password/route.js, app/reset-password/page.jsx, app/seller/(auth)/forgot-password/page.jsx, app/seller/(auth)/login/page.jsx, app/seller/layout.jsx
- add a seller-specific forgot password API that verifies seller accounts and generates reset links
- build a dedicated seller forgot password page and link it from the seller login screen
- allow the shared reset-password page to respect redirect targets so sellers return to their login flow
=> Add seller forgot password flow

app/signup/page.jsx
- Rebuilt the seller signup experience with a gradient backdrop, animated hero, and responsive two-column layout that mirrors the login page styling.
- Refreshed form components with rounded inputs, improved spacing, and polished button states for both account creation and OTP verification steps.
=> Redesign seller signup page for responsive layout

components/BuyerPanel/products/ProductDetail.jsx
- refresh the seller details card on the product detail page with branding, verification, contact, and address information for a richer presentation
- add helper utilities to derive seller initials and head office address details used in the updated layout
=> Enhance seller information on product detail page

app/seller/page.jsx, middleware.js
- rebuild the /seller landing experience with a cohesive SafeTrade-inspired gradient theme, refreshed content, and new CTA flows
- highlight key features, seller journey, product verticals, testimonials, and FAQs directly on the page for a single high-performance entry point
- update middleware to mark /seller as a public route so prospects can access the marketing page without authenticating
=> Redesign seller landing page and allow public access

app/(buyers)/reviews/[orderId]/page.jsx
- normalize products returned from the order API so the rate & review form always has product data
- fall back to sub-order items when no top-level products are present and guard the UI when nothing is reviewable
- ensure review form state uses stable string keys for each product before submitting reviews
=> Fix rate & review page crash when order lacks products list

app/api/auth/signup/route.js, app/api/orders/route.js, lib/orders/email.js
- send a customer welcome email and an admin-only notification when a new user completes signup
- add reusable helpers for building admin order emails and trigger them whenever a new order is created
=> Add admin email notifications for signups and orders
